version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sfgov
      POSTGRES_PASSWORD: sfgov_local
      POSTGRES_DB: sf_governance
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
